// angular/src/app/todo-form/todo-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-todo-form',
  templateUrl: './todo-form.component.html',
  styleUrls: ['./todo-form.component.css'],
})
export class TodoFormComponent implements OnInit {
  constructor(private formBuilder: FormBuilder) {}

  todoForm = this.formBuilder.group({ todo: '' });

  ngOnInit(): void {}

  onSubmit = (): void => {
    console.log(this.todoForm.value);
    this.todoForm.reset();

  };
}

<form [formGroup]="todoForm" (ngSubmit)="onSubmit()">
  <input type="text" formControlName="todo" />
  <button type="submit">확인</button>
</form>

// vue/src/components/TodoForm.vue
<template>
  <form v-on:submit.prevent="onSubmit">
    <input type="text" v-model="input" />
    <button type="submit">확인</button>
  </form>
</template>

<script>
export default {
  name: "TodoForm",
  data() {
    return { input: "" };
  },
  methods: {
    onSubmit: function () {
      console.log(this.input);
      this.input = "";
    },
  },
};
</script>

<style scoped>
</style>
