// vue/src/App.vue
<template>
  <div>
    <h1>oh to dos vue</h1>
    <TodoList />
    <TodoForm />
  </div>
</template>

<script>
import TodoForm from "./components/TodoForm.vue";
import TodoList from "./components/TodoList.vue";

export default {
  name: "App",
  components: {
    TodoList,
    TodoForm,
  },
};
</script>

<style></style>

// react/src/App.tsx
import TodoForm from "./components/TodoForm";
import TodoList from "./components/TodoList";
import useTodos from "./hooks/useTodos";

function App() {
  const { todos } = useTodos();

  return (
    <div>
      <h1>oh to do react</h1>
      <TodoList todos={todos} />
      <TodoForm />
    </div>
  );
}

export default App;
