// vue/src/components/TodoList.vue
<template>
  <div>
    <ul v-for="todo in todos" :key="todo.id">
      <li :id="todo.id">
        {{ todo.fields.name }}
        <button v-on:click="onDeleteClick">X</button>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: "TodoList",
  props: ["todoList", "deleteTodo"],
  computed: {
    todos: function () {
      const p = new Proxy(this.todoList, {});
      return JSON.parse(JSON.stringify(p));
    },
  },
  methods: {
    onDeleteClick: function (e) {
      const { id } = e.target.parentNode;
      this.deleteTodo(id);
    },
  },
};
</script>

<style scoped>
</style>

// nextjs/src/components/TodoList.jsx
import useTodos from "../hooks/useTodos";

function TodoList() {
  const { data, error, deleteTodo } = useTodos();

  function onClickDelete(e) {
    const { id } = e.currentTarget.parentNode;
    deleteTodo(id);
  }

  if (error) return <div>error</div>;
  if (!data) return <div>loading...</div>;

  return (
    <ul>
      {data.records.map((todo) => (
        <li key={todo.id} id={todo.id}>
          {todo.fields.name}
          <button onClick={onClickDelete}>X</button>
        </li>
      ))}
    </ul>
  );
}

export default TodoList;
