// vue/src/components/TodoForm.vue
<template>
  <form v-on:submit.prevent="onSubmit">
    <input type="text" v-model="input" />
    <button type="submit">확인</button>
  </form>
</template>

<script>
export default {
  name: "TodoForm",
  props: ["createTodo"],
  data() {
    return { input: "" };
  },
  methods: {
    onSubmit: function () {
      this.createTodo(this.input);
      this.input = "";
    },
  },
};
</script>

<style scoped>
</style>

// nextjs/src/components/TodoForm.jsx
import { useRef } from "react";
import useTodos from "../hooks/useTodos";

function TodoForm() {
  const { createTodo } = useTodos();
  const inputRef = useRef();

  function onSubmit(e) {
    e.preventDefault();
    createTodo(inputRef.current.value);
    inputRef.current.value = "";
  }

  return (
    <form onSubmit={onSubmit}>
      <input type="text" ref={inputRef} />
      <button type="submit">확인</button>
    </form>
  );
}

export default TodoForm;
