// vue/src/components/TodoForm.vue
<template>
  <form v-on:submit.prevent="onSubmit">
    <input type="text" v-model="input" />
    <button type="submit">확인</button>
  </form>
</template>

<script>
export default {
  name: "TodoForm",
  props: ["createTodo"],
  data() {
    return { input: "" };
  },
  methods: {
    onSubmit: function () {
      this.createTodo(this.input);
      this.input = "";
    },
  },
};
</script>

<style scoped>
</style>

// react/src/components/TodoForm.tsx
import { FormEvent, useRef } from "react";

interface TodoFormProps {
  createTodo: (todoString: string) => void;
}

function TodoForm({ createTodo }: TodoFormProps) {
  const inputRef = useRef<HTMLInputElement>(null);

  const onSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!inputRef.current) return;

    createTodo(inputRef.current.value);
    inputRef.current.value = "";
  };

  return (
    <form onSubmit={onSubmit}>
      <input type="text" ref={inputRef} />
      <button type="submit">확인</button>
    </form>
  );
}

export default TodoForm;
